# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VisicomReverseGeocoder
                                 A QGIS plugin
 plugin for reverse geocoding from visicom api
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-09-21
        copyright            : (C) 2018 by zimirrr
        email                : zimirrr@mail.ru
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load VisicomReverseGeocoder class from file VisicomReverseGeocoder.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .visicom_reverse_geocoding import VisicomReverseGeocoder
    return VisicomReverseGeocoder(iface)
